[build-system]
requires = ["setuptools"]

[project]
name = "superdesk-analytics"
version = "3.2.0-dev.0"
authors = [ {name = "Sourcefabric", email = "contact@sourcefabric.org"} ]
readme = "README.md"
license = "MIT"
dependencies = [

]

[tool.setuptools]
package-dir = {"" = "server"}

[tool.setuptools.package-data]
analytics = ["scripts/*.sh"]

[tool.setuptools.packages.find]
where = ["server"]
include = ["server"]
exclude = ["client", "spec"]

[tool.black]
line-length = 120
target-version = ['py38']
include = '\.py$'
exclude = '''
(
    \.eggs
    | \.git
    | \.mypy_cache
    | \.tox
    | \.env
    | _build
    | build
    | dist
    | env
)
'''

[tool.pytest.ini_options]
testpaths = ["server/analytics"]
python_files = "*_test.py *_tests.py test_*.py tests_*.py tests.py test.py"
